#!/usr/bin/env bash

set -euxo pipefail


echo $RESOURCE > resource.yaml

if [ $VERSION = "v1alpha1" ]; then
	echo "converting from v1alpha to v1beta1"
	container0="$(cat resource.yaml | yq .spec.container0Cmd)"
	container1="$(cat resource.yaml | yq .spec.container1Cmd)"
	name="$(cat resource.yaml | yq .metadata.name)"
	namespace="$(cat resource.yaml | yq .metadata.namespace)"

	echo $container0
	echo $container1

	echo """---
apiVersion: test.kratix.io/v1beta1
kind: bash
metadata:
  name: ${name}
  namespace: ${namespace}
spec:
  container:
    cmd0: ${container0}
    cmd1: ${container1}
""" > /output/resource.yaml
else
	echo "converting from v1beta1 to v1alpha1"
	container0="$(cat resource.yaml | yq .spec.container.cmd0)"
	container1="$(cat resource.yaml | yq .spec.container.cmd1)"
	name="$(cat resource.yaml | yq .metadata.name)"
	namespace="$(cat resource.yaml | yq .metadata.namespace)"

	echo $container0
	echo $container1

	echo """---
apiVersion: test.kratix.io/v1alpha1
kind: bash
metadata:
  name: ${name}
  namespace: ${namespace}
spec:
  container0Cmd: ${container0}
  container1Cmd: ${container1}
""" > /output/resource.yaml
fi
