apiVersion: platform.kratix.io/v1alpha1
kind: Promise
metadata:
  name: jenkins
  namespace: default
spec:
  api:
    version: v1alpha1
    kind: jenkins
    group: acme.org.io
    template:
      name: ""
      port: 0
      tlsEnabld: false
      config: {}
      plugins:
        - ""
      additionalPorts:
        - 0
      somethingRequiringBoolArray:
        - false
      users:
        - name: ""
          permissions: ""
      teamConfigs: [{}]
      startUpArgs: []
  xaasRequestPipeline:
    - syntassodev/bash-promise-test-c0:dev
  workerClusterResources:
    - apiVersion: v1
      kind: Namespace
      metadata:
        name: bash-wcr-namespace
