apiVersion: platform.kratix.io/v1alpha1
kind: Promise
metadata:
  name: bbp
  namespace: default
spec:
  dependencies:
  - name: jenkins
    version: v1alpha1
  - name: istio
    version: v1alpha1
  xaasCrd:
    apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    metadata:
      name: bbps.marketplace.kratix.io
    spec:
      group: marketplace.kratix.io
      names:
        kind: bbp
        plural: bbps
        singular: bbp
      scope: Namespaced
      versions:
        - name: v1alpha1
          schema:
            openAPIV3Schema:
              properties:
                spec:
                  required:
                    - message
                  properties:
                    message:
                      type: string
                      description: |
                        The message to be sent
                  type: object
              type: object
          served: true
          storage: true
  xaasRequestPipeline:
    - ghcr.io/syntasso/kratix-marketplace/bbp-request-pipeline:v0.1.0
