---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tfstate-finder-test
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
  - apiGroups:
      - platform.kratix.io
    resources:
      - workplacements
      - destinations
    verbs:
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tfstate-finder-test-resource
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tfstate-finder-test
subjects:
  - kind: ServiceAccount
    name: redis-resource-pipeline
    namespace: default

