apiVersion: platform.kratix.io/v1alpha1
kind: Promise
metadata:
  name: paved-path
  namespace: default
spec:
  dependencies:
  - name: knative
    version: v1alpha1
  - name: postgresql
    version: v1alpha1
    clusterSelectorOverride:
      environment: dev
  xaasCrd:
    apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    metadata:
      name: paved-path-demos.example.promise.syntasso.io
    spec:
      group: example.promise.syntasso.io
      names:
        kind: paved-path-demo
        plural: paved-path-demos
        singular: paved-path-demo
      scope: Namespaced
      versions:
        - name: v1
          schema:
            openAPIV3Schema:
              properties:
                spec:
                  properties:
                    name:
                      type: string
                  type: object
              type: object
          served: true
          storage: true
  xaasRequestPipeline:
    - syntasso/paved-path-demo-request-pipeline
