---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - platform.kratix.io
  resources:
  - clusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - platform.kratix.io
  resources:
  - clusters/finalizers
  verbs:
  - update
- apiGroups:
  - platform.kratix.io
  resources:
  - clusters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - platform.kratix.io
  resources:
  - promises
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - platform.kratix.io
  resources:
  - promises/finalizers
  verbs:
  - update
- apiGroups:
  - platform.kratix.io
  resources:
  - promises/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - platform.kratix.io
  resources:
  - workplacements
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - platform.kratix.io
  resources:
  - workplacements/finalizers
  verbs:
  - update
- apiGroups:
  - platform.kratix.io
  resources:
  - workplacements/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - platform.kratix.io
  resources:
  - works
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - platform.kratix.io
  resources:
  - works/finalizers
  verbs:
  - update
- apiGroups:
  - platform.kratix.io
  resources:
  - works/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterroles
  verbs:
  - bind
  - create
  - delete
  - escalate
  - get
  - list
  - watch
