apiVersion: platform.kratix.io/v1alpha1
kind: Promise
metadata:
  creationTimestamp: null
  name: kafka
  namespace: default
spec:
  workerClusterResourcesImages:
    - "demo.goharbor.io/syntassodev/kafka-worker-cluster-resources:latest"
  xaasCrd:
    apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    metadata:
      name: kafka.marketplace.kratix.io
    spec:
      group: marketplace.kratix.io
      names:
        kind: kafka
        plural: kafka
        singular: kafka
      scope: Namespaced
      versions:
      - name: v1alpha1
        schema:
          openAPIV3Schema:
            properties:
              spec:
                properties:
                  size:
                    default: small
                    description: |
                      Size of this kafka deployment. If small, it deploy kafka with a single replica; if large, deploy kafka with 3 replicas.
                    pattern: ^(small|large)$
                    type: string
                type: object
            type: object
        served: true
        storage: true
  xaasRequestPipeline:
  - ghcr.io/syntasso/kratix-marketplace/kafka-request-pipeline:v0.1.0
status: {}
