// Package metrics exposes gauges describing the current state of the platform:
// how many Promises are available, which Destinations are ready, and how the
// Works generated by resource requests and promises are being scheduled.
package metrics

import (
	"context"

	"github.com/go-logr/logr"
	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/attribute"
	"go.opentelemetry.io/otel/metric"
	apimeta "k8s.io/apimachinery/pkg/api/meta"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"sigs.k8s.io/controller-runtime/pkg/client"

	"github.com/syntasso/kratix/api/v1alpha1"
	"github.com/syntasso/kratix/internal/logging"
)

const (
	instrumentationName = "github.com/syntasso/kratix/internal/metrics"

	PromiseAvailableMetric = "kratix_promise_available"
	DestinationReadyMetric = "kratix_destination_ready"
	WorksMetric            = "kratix_works"

	WorkStatusReady       = "ready"
	WorkStatusUnscheduled = "unscheduled"
	WorkStatusMisplaced   = "misplaced"
	WorkStatusFailing     = "failing"
	WorkStatusPending     = "pending"

	readyConditionType = "Ready"
)

// RegisterPlatformStateGauges registers observable gauges that report the current state
// of Promises, Destinations and Works on every metrics collection. The reader is expected
// to be backed by the manager's cache; list errors (for example before the cache has
// started) are logged and result in no observations for that collection.
func RegisterPlatformStateGauges(logger logr.Logger, reader client.Reader) (metric.Registration, error) {
	meter := otel.Meter(instrumentationName)

	promiseAvailableGauge, err := meter.Int64ObservableGauge(
		PromiseAvailableMetric,
		metric.WithDescription("Whether each Promise is Available (1) or Unavailable (0)"),
	)
	if err != nil {
		return nil, err
	}

	destinationReadyGauge, err := meter.Int64ObservableGauge(
		DestinationReadyMetric,
		metric.WithDescription("Whether each Destination is Ready (1) or not (0)"),
	)
	if err != nil {
		return nil, err
	}

	worksGauge, err := meter.Int64ObservableGauge(
		WorksMetric,
		metric.WithDescription("Number of Works grouped by promise, work type, and scheduling status"),
	)
	if err != nil {
		return nil, err
	}

	return meter.RegisterCallback(func(ctx context.Context, observer metric.Observer) error {
		observePromiseAvailability(ctx, observer, promiseAvailableGauge, reader, logger)
		observeDestinationReadiness(ctx, observer, destinationReadyGauge, reader, logger)
		observeWorks(ctx, observer, worksGauge, reader, logger)
		return nil
	}, promiseAvailableGauge, destinationReadyGauge, worksGauge)
}

func observePromiseAvailability(ctx context.Context, observer metric.Observer, gauge metric.Int64ObservableGauge, reader client.Reader, logger logr.Logger) {
	promises := &v1alpha1.PromiseList{}
	if err := reader.List(ctx, promises); err != nil {
		logging.Debug(logger, "unable to list Promises for metrics collection", "error", err)
		return
	}

	for _, promise := range promises.Items {
		var available int64
		condition := promise.GetCondition(v1alpha1.PromiseAvailableConditionType)
		if condition != nil && condition.Status == metav1.ConditionTrue {
			available = 1
		}
		observer.ObserveInt64(gauge, available, metric.WithAttributes(
			attribute.String("promise", promise.GetName()),
		))
	}
}

func observeDestinationReadiness(ctx context.Context, observer metric.Observer, gauge metric.Int64ObservableGauge, reader client.Reader, logger logr.Logger) {
	destinations := &v1alpha1.DestinationList{}
	if err := reader.List(ctx, destinations); err != nil {
		logging.Debug(logger, "unable to list Destinations for metrics collection", "error", err)
		return
	}

	for _, destination := range destinations.Items {
		var ready int64
		condition := apimeta.FindStatusCondition(destination.Status.Conditions, readyConditionType)
		if condition != nil && condition.Status == metav1.ConditionTrue {
			ready = 1
		}
		observer.ObserveInt64(gauge, ready, metric.WithAttributes(
			attribute.String("destination", destination.GetName()),
		))
	}
}

type workGroup struct {
	promise  string
	workType string
	status   string
}

func observeWorks(ctx context.Context, observer metric.Observer, gauge metric.Int64ObservableGauge, reader client.Reader, logger logr.Logger) {
	works := &v1alpha1.WorkList{}
	if err := reader.List(ctx, works); err != nil {
		logging.Debug(logger, "unable to list Works for metrics collection", "error", err)
		return
	}

	counts := map[workGroup]int64{}
	for _, work := range works.Items {
		workType := v1alpha1.WorkTypePromise
		if work.IsResourceRequest() {
			workType = v1alpha1.WorkTypeResource
		}
		counts[workGroup{
			promise:  work.Spec.PromiseName,
			workType: workType,
			status:   workSchedulingStatus(&work),
		}]++
	}

	for group, count := range counts {
		observer.ObserveInt64(gauge, count, metric.WithAttributes(
			attribute.String("promise", group.promise),
			attribute.String("work_type", group.workType),
			attribute.String("status", group.status),
		))
	}
}

// workSchedulingStatus derives a single scheduling status from the Work's Ready condition,
// mirroring the reasons set by the scheduler and the Work controller.
func workSchedulingStatus(work *v1alpha1.Work) string {
	condition := apimeta.FindStatusCondition(work.Status.Conditions, readyConditionType)
	if condition == nil {
		return WorkStatusPending
	}
	if condition.Status == metav1.ConditionTrue {
		return WorkStatusReady
	}

	switch condition.Reason {
	case "UnscheduledWorkloads":
		return WorkStatusUnscheduled
	case "Misplaced":
		return WorkStatusMisplaced
	case "WorkplacementsFailing":
		return WorkStatusFailing
	}
	return WorkStatusPending
}
